import { Outfit } from "next/font/google";
import "./globals.css";
import { PlayerProvider } from "./music/context/PlayerContext";
import MusicPlayer from "./music/components/MusicPlayer";
import { customFont } from "./fonts";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "Echo: listen music flowlessly",
  description: "Generated by create next app",

  // ✅ Add all PWA icons here
  icons: {
    icon: "/hel.svg", // your current icon
    apple: "/apple-touch-icon.png",
  },

  // ✅ Add manifest here
  manifest: "/manifest.json",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${outfit.variable} ${customFont.variable}`}>
      <head>
        <meta
          name="google-site-verification"
          content="googleaadf1a5d11837f5a.html"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </head>

      <body className="font-sans antialiased bg-white text-gray-900">
        <PlayerProvider>
          {children}
          <MusicPlayer />
        </PlayerProvider>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Disable right-click context menu
              document.addEventListener('contextmenu', function(e) {
                e.preventDefault();
              });

              // Disable Ctrl+/- and Ctrl+0 zoom shortcuts
              document.addEventListener('keydown', function(e) {
                if ((e.ctrlKey || e.metaKey) && (e.key === '+' || e.key === '-' || e.key === '=' || e.key === '0')) {
                  e.preventDefault();
                }
              });

              // Disable Ctrl+scroll wheel zoom
              document.addEventListener('wheel', function(e) {
                if (e.ctrlKey) {
                  e.preventDefault();
                }
              }, { passive: false });
            `,
          }}
        />
      </body>
    </html>
  );
}
