import { Outfit } from "next/font/google";
import "./globals.css";
import { PlayerProvider } from "./music/context/PlayerContext";
import MusicPlayer from "./music/components/MusicPlayer";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "Echo: listen music flowlessly",
  description: "Generated by create next app",
  icons: {
    icon: "/hel.svg", // 👈 your favicon here
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} font-sans antialiased bg-white text-gray-900`}
      >
        <PlayerProvider>
          {children}
          <MusicPlayer />
        </PlayerProvider>
      </body>
    </html>
  );
}
